apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibhor
  labels:
    app: vibhor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vibhor
  template:
    metadata:
      labels:
        app: vibhor
    spec:
      containers:
      - name: vibhor
        image: vibhors1995/vibhor132103
        ports:
        - containerPort: 80
